### ISSUE TITLE
fbx python binding install error

### ISSUE THREAD

**Issue by hhebb** [NVlabs/CALM#10]
i want to load my fbx file.
but i can't install autodesk's fbx binding.
i tried fbx 202032, 202034 (for only python3.10 whl) but failed.
build sip 4.19.3 package manually, but finally still stucked.
is anyone successfully install fbx bindings, load fbx file??

thanks

**Comment by 1311894932** [comment]
May I ask if your program is running normally

**Comment by 1311894932** [comment]
hi, may I ask if your program is running normally

**Comment by hhebb** [comment]
model training is executed normally.
but failed to install fbx binding.

my system is
ubuntu 20.04
python3.8.10

thanks.

**Comment by 1311894932** [comment]
author's answer: https://github.com/nv-tlabs/ASE/issues/10

**Comment by hhebb** [comment]
it solved.
with https://github.com/nv-tlabs/ASE/issues/40#issuecomment-1518829099
thanks a lot #
