### ISSUE TITLE
File "calm/run.py", line 200, in build_alg_runner     runner.model_builder.model_factory.register_builder('amp', lambda network, **kwargs: amp_models.ModelAMPContinuous(network)) AttributeError: 'Runner' object has no attribute 'model_builder'

### ISSUE THREAD

**Issue by dccdcc7** [NVlabs/CALM#14]

**Comment by dccdcc7** [comment]
Which version has this '.model_builder.model_factory.register_builder' in lr_games

**Comment by GuoShuaiGO** [comment]
Have you solved the problem? I have the same problem you have

**Comment by tesslerc** [comment]
Have you tried using a different version of RLgames? I haven't seen this issue in the past.
