### ISSUE TITLE
Poselib: CMU MoCap dataset

### ISSUE THREAD

**Issue by chenyunzhanggit** [NVlabs/CALM#15]
Thank you for everything you do!

When I try to replac fbx dataset(like 01_01_cmu.fbx, 07_01_cmu.fbx) I downloaded from other resources, the coordinate axes in the visualization interface became incorrect, and the movement was along the z direction.

With 01_01_cmu.fbx you provided:
![image](https://github.com/user-attachments/assets/4380865f-2a65-4e2b-acb8-8d530c322b9d)

With 01_01.fbx I downloaded from other resources:
![01_01](https://github.com/user-attachments/assets/1a28642d-f0c2-42dd-8ce8-7335b2d875ca)

Can you share the way you process the original data? Or can you share the correct dataset?

Thanks!

**Comment by tesslerc** [comment]
By default the SMPL motions are with Y-up.
In Isaac we typically use Z-up.
To account for that, we rotate the motions.

See example in PHC: https://github.com/ZhengyiLuo/PHC/blob/6db1db1830b513f670525a2046d28fe51d0e77d2/scripts/data_process/convert_amass_isaac.py#L111

**Comment by chenyunzhanggit** [comment]
Alright, let me give it a shot. Thank you so much!

**Comment by tesslerc** [comment]
I forgot to mention.
The original dataset is in https://github.com/nv-tlabs/ASE/tree/main/ase/data/motions/reallusion_sword_shield
We used the AMP humanoid in both works, it has a reduced DoF compared to SMPL.
The AMASS dataset is SMPL so if you want to use the amass dataset, you'll also have to retarget the motion to the AMP humanoid for it to work.

Alternatively, you can swap to the SMPL humanoid. There's an example in the PHC codebase.
