### ISSUE TITLE
CALM precision training with heading conditioning fails

### ISSUE THREAD

**Issue by VineetTambe** [NVlabs/CALM#17]
I have a low level policies which I have trained  on a certain set of retargetted motions for which I would like to train a high level policy.
From what I understand the motion_files I use for this part of training should only contain the subset of the llc training which comprise the "FSM".

However, training a `HumanoidHeadingConditioned` policy fails to follow the target heading when I run the precision training. 
Am I missing something here? 
Is there any other training param that I should adapt for my use case?

I have not changed anything in the `HumanoidHeadingConditioned` class - only changes are in the `AMPHumanoid` and `Humanoid` classes and given that the llc trains somewhat to generate the reference data - I was expecting the rest of the pipeline to work as is without much modification.

Thanks for the help in advance!

**Comment by VineetTambe** [comment]
Any update on this? 
Should I change the weight of the task reward in the heading condition python class?

**Comment by tesslerc** [comment]
You need to have a motion file for the heading motions, for example `dataset_reallusion_sword_shield_fsm_movements.yaml`.

I would try tweaking the task reward and see if that helps. Set it to 1 for task and 0 for style just as a sanity check.
