### ISSUE TITLE
Exporting an onnx file

### ISSUE THREAD

**Issue by VineetTambe** [NVlabs/CALM#19]
Hey Authors,
Thanks for answering all my questions in the previous posts. They helped me gain a deeper understanding of how CALM works. 

I wanted to know how do I go about exporting an .onnx file? 

I am a little lost in the chain of inherited classes in the model architecture.
I am trying to modify the `run.py` file by adding an export to onnx function which takes in the instance of `runner`

But I am unsure how the input_dict and output_dict should be structured.
I was trying to use [this guide](https://www.tylerbarkin.com/isaac-gym-to-onnx) as reference but it has left me more confused :/

Any help would be appreciated :)

Thanks 

Edit:

To be specific:
1. What am I supposed to pass in the `prev_actions` and `rnn_states`?

or would something like the following work?
```
input_dict = {
            'is_train': False,
            'prev_actions': None,
            'obs': obs,
            'rnn_states': None,
            'calm_latents': self.calm_latents
        }
```

From what I understand the observation tensor for calm llc is 64D latent + the obs_state vector defined in the environment.
The `prev_action` confuse me.

**Comment by tesslerc** [comment]
Unfortunately we don't have experience with exporting to onnx.
I think you are right and `prev_actions` and `rnn_states` should be set to `None` when performing inference.

**Comment by VineetTambe** [comment]
Okay, gotcha.

A follow up to this - 
I have set my observation returned by my humanoid class to be a `n_env x 79` which when stacked becomes `n x 6 x 79`

But when I am trying to export the `onnx` by getting the observation in `run.py` I get a `n_env x 508` obs tensor.
Could you point me towards where I can find the exact place where this observation is being constructed?
I was expecting this tensor to be `n_env x 474` but there are somehow extra 34 columns.
