### ISSUE TITLE
No pre-trained model

### ISSUE THREAD

**Issue by ZQX323** [NVlabs/CALM#2]
Hello,
I am trying to use the pre-trained model for the sword and shield
. However, I was unable to locate the pre-trained model at the expected location "calm/data/models/calm_llc_reallusion_sword_shield.pth".
Can someone please help me to upload the pre-trained model?
Thank you.

**Comment by tesslerc** [comment]
We currently have an issue with LFS. Until we fix it, the models are available here:
https://drive.google.com/drive/folders/1_fEN-KN24Hb5VgQeAZvgiKV3CqeT_hc-?usp=sharing

**Comment by tesslerc** [comment]
Models have now been uploaded to LFS.
