### ISSUE TITLE
IsaacLab version code

### ISSUE THREAD

**Issue by servingrobotmaster** [NVlabs/CALM#21]
hello. Thank you for introducing the contents of this excellent thesis. I have one request. I would like to ask if there is any code for isaaclab other than isaacsim.

**Comment by tesslerc** [comment]
This code is provided as is. It's only IsaacGym.
[ProtoMotions](https://github.com/NVlabs/ProtoMotions) follows our more recent efforts. It's updated and also contains IsaacSim examples.
