### ISSUE TITLE
[Question] observation input to the actor and critic.

### ISSUE THREAD

**Issue by VineetTambe** [NVlabs/CALM#22]
Hey Authors,

I was going through the code again and am a little bit confused and had the following questions regarding the input to the actor and critic:
1. Do actor and critic use the same observations? If not the - 
2. Is `compute_humanoid_observations_max()` used to compute the actor's observation? 
3. Is `build_amp_observations()` used to compute the observation for critic? As it contains privileged information in the form of `keybody_ids`?

Any clarification would be helpful! 
Thanks

**Comment by tesslerc** [comment]
Both models observe the same base "obs" but you can pass each model additional (and different) inputs.
Indeed both observe `compute_humanoid_observations_max`.

The amp_obs are used for the discriminator when training AMP/ASE.

**Comment by VineetTambe** [comment]
Thanks for the quick reply! 

Could you point me to where in the codebase I have to make changes in order to separate the actor's observation the critic observation?
I am a little bit lost in the way the things are implemented as the `a_loss` and `c_loss` don't directly use the observation but instead get values from a buffer. I am guessing I need to modify this buffer somehow but - so would I be correct in assuming that I need to create a new buffer and update it in the environment so that the `c_loss` can use the privileged information?

**Comment by tesslerc** [comment]
You can see the data dict created here: https://github.com/NVlabs/CALM/blob/4f6bdb9d6536d3075b83bcfc8e066c331700faa0/calm/learning/amp_agent.py#L335

Here is the forward function for actor and critic: https://github.com/NVlabs/CALM/blob/4f6bdb9d6536d3075b83bcfc8e066c331700faa0/calm/learning/amp_network_builder.py#L66

You can create the dict with "actor_obs" and "critic_obs" and then in the forward pass provide each network with its own observation.
