### ISSUE TITLE
Exception invalid load key, 'v'. when trying to execute

### ISSUE THREAD

**Issue by Robokan** [NVlabs/CALM#7]
Thanks for posting the ASC and CALM code bases they have been very helpful to understand the papers.
Unfortunately when trying the examples there seems to be a problem loading the pretrained llc file. 

python calm/run.py --test --task HumanoidStrikeFSM --num_envs 16 --cfg_env calm/data/cfg/humanoid_sword_shield_strike_fsm.yaml --cfg_train calm/data/cfg/train/rlg/hrl_humanoid_fsm.yaml --motion_file calm/data/motions/reallusion_sword_shield/dataset_reallusion_sword_shield_fsm_movements.yaml --llc_checkpoint calm/data/models/calm_llc_reallusion_sword_shield.pth --checkpoint calm/data/cfg/humanoid_sword_shield_strike_fsm.yaml

=> loading checkpoint 'calm/data/models/calm_llc_reallusion_sword_shield.pth'
Exception invalid load key, 'v'. when trying to execute <function load at 0x7f653a9b8940> with args:('calm/data/models/calm_llc_reallusion_sword_shield.pth',) and kwargs:{}...

**Comment by Croolch** [comment]
did you check the pth file? it seems need to be downloaded first

```
version https://git-lfs.github.com/spec/v1
oid sha256:0d71028bf8b6accdc4ac5b5255582e16bd8290c3c7829746f86eb0389a2f63a2
size 19332096
```

**Comment by Croolch** [comment]
i used llc_checkpoint from [ASE](https://github.com/nv-tlabs/ASE/tree/main/ase/data/models) and it worked. This is a kind of try for making sure the problem happened in the pth file.

**Comment by Croolch** [comment]
you need to install [git lfs](https://git-lfs.com/) and run `git lfs pull` to download pth files

**Comment by Robokan** [comment]
Ok it works now that I download the model with lfs. I also needed to adjust the command to:

python calm/run.py --test --task HumanoidStrikeFSM --num_envs 16 --cfg_env calm/data/cfg/humanoid_sword_shield_strike_fsm.yaml --cfg_train calm/data/cfg/train/rlg/hrl_humanoid_fsm.yaml --motion_file calm/data/motions/reallusion_sword_shield/dataset_reallusion_sword_shield_fsm_movements.yaml --llc_checkpoint calm/data/models/calm_llc_reallusion_sword_shield.pth --checkpoint calm/data/models/calm_hlc_precision_trained_reallusion_sword_shield.pth

but it works now! Thanks
