### ISSUE TITLE
Error in precision training

### ISSUE THREAD

**Issue by yoyostudy** [NVlabs/CALM#9]
Hi, 

I was running code for testing precision-training and it returned error:

```
=> loading checkpoint 'Base'
Exception [Errno 2] No such file or directory: 'Base' when trying to execute <function load at 0x7ff0fcb94790> with args:('Base',) and kwargs:{}...
```

Any idea of how to fix it?

Thank you so much!

**Comment by tesslerc** [comment]
Can you share the command you used?
Also did you make sure to download the models from lfs, assuming you didn't train them yourself?

Thanks
